# Generated by Django 4.1.7 on 2023-03-28 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examinee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_completed_exam', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_mcq_option', models.CharField(choices=[('mcq_option1', 'Option 1'), ('mcq_option2', 'Option 2'), ('mcq_option3', 'Option 3'), ('mcq_option4', 'Option 4')], max_length=25, null=True)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('Long Answer', 'Long Answer')], max_length=15)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(null=True)),
                ('mcq_option1', models.CharField(max_length=255, null=True)),
                ('mcq_option2', models.CharField(max_length=255, null=True)),
                ('mcq_option3', models.CharField(max_length=255, null=True)),
                ('mcq_option4', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_mcq_option', models.CharField(choices=[('mcq_option1', 'Option 1'), ('mcq_option1', 'Option 2'), ('mcq_option1', 'Option 3'), ('mcq_option1', 'Option 4')], max_length=25, null=True)),
                ('selected_long_answer', models.TextField(null=True)),
                ('examinee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.examinee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.subject'),
        ),
    ]
