# Generated by Django 4.1.7 on 2023-03-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0002_remove_subject_end_time_remove_subject_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedanswer',
            name='selected_mcq_option',
            field=models.CharField(choices=[('mcq_option1', 'Option 1'), ('mcq_option2', 'Option 2'), ('mcq_option3', 'Option 3'), ('mcq_option4', 'Option 4')], max_length=25, null=True),
        ),
    ]
