# Generated by Django 4.1.7 on 2023-04-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0003_alter_selectedanswer_selected_mcq_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=15),
            preserve_default=False,
        ),
    ]
